# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0002_auto_20170311_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('login', 'login'), ('start-a-review-session', 'start-a-review-session'), ('ending-a-review-session', 'ending-a-review-session')], max_length=80)),
                ('ua_string', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('referrer', models.CharField(blank=True, max_length=511, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_pk', models.IntegerField()),
                ('other_info', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Person')),
            ],
        ),
    ]
