# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='item_pk',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
