# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170313_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='event',
            field=models.CharField(choices=[('login', 'login'), ('start-a-review-session', 'start-a-review-session'), ('continue-review-session', 'continue-review-session'), ('ending-a-review-session', 'ending-a-review-session'), ('reviewing-feedback', 'reviewing-feedback')], max_length=80),
        ),
    ]
