# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0026_course_base_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_value', models.DecimalField(decimal_places=2, help_text='A value between 0 and 100.', max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, help_text='A value between 0 and 100. Normally this is 100.0', max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Course')),
            ],
        ),
        migrations.CreateModel(
            name='GradeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Which column order is this item')),
                ('max_score', models.DecimalField(decimal_places=2, default=100, help_text='The largest value a student can achieve for this item', max_digits=5)),
                ('link', models.CharField(blank=True, max_length=600, verbose_name='The link to the page where the student can complete this; begin link after the base URL: /courseware/...')),
                ('weight', models.DecimalField(decimal_places=3, help_text='The weight of this item; a value between 0.0 and 1.0', max_digits=4)),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.GradeBook')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, help_text='The grade earned by the learner.', max_digits=7)),
                ('gitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.GradeItem')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Person')),
            ],
        ),
    ]
