# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecategory',
            name='spread_evenly',
            field=models.BooleanField(default=True, help_text='Spread weight across all items evenly. True: no need to specify weights on the GradeItems. '),
        ),
    ]
