# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_gradecategory_spread_evenly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeitem',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=-1.0, help_text='The weight of this item; a value between 0.0 and 1.0', max_digits=4),
        ),
    ]
