# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_auto_20170430_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeitem',
            name='link',
            field=models.CharField(blank=True, help_text='The link to the page where the student can complete this; begin link after the base URL: /courseware/...', max_length=600),
        ),
        migrations.AlterField(
            model_name='gradeitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=-1.0, help_text='The weight of this item; a value between 0.0 and 1.0. If weight=-1.0, then the weight is determined by the category, which will assign equal weight to all items.', max_digits=4),
        ),
    ]
