# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_auto_20170430_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnergrade',
            name='modfied_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='learnergrade',
            name='not_graded_yet',
            field=models.BooleanField(default=True, help_text='If this item is not yet graded/submitted/etc'),
        ),
    ]
