# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_auto_20170430_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnergrade',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The grade earned by the learner.', max_digits=7, null=True),
        ),
    ]
