# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import review.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Course name')),
                ('label', models.CharField(max_length=300, verbose_name='LTI POST label')),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Group name')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='First name')),
                ('is_active', models.BooleanField(default=True, help_text='Placeholder')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PR_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LTI_system', models.CharField(choices=[('Brightspace-v1', 'Brightspace-v1'), ('edX-v1', 'edX-v1')], max_length=50)),
                ('title', models.CharField(max_length=300, verbose_name='Peer review')),
                ('slug', models.SlugField(default='')),
                ('instructions', models.TextField(help_text='May contain HTML instructions', verbose_name='Overall instructions to learners')),
                ('submission_deadline', models.DateTimeField(verbose_name='When should learners submit their work by')),
                ('peer_reviews_start_by', models.DateTimeField(verbose_name='When does the reviewing step open?')),
                ('peer_reviews_completed_by', models.DateTimeField(verbose_name='When must learners submit their reviews by?')),
                ('peer_reviews_received_back', models.DateTimeField(verbose_name='When will learners receive their reviews back?')),
                ('show_rubric_prior_to_submission', models.BooleanField(default=False, help_text='Can learners see the rubric before they submit?')),
                ('all_submissions_visible_after_review', models.BooleanField(default=False, help_text='Can learners see all submissions from peers after the reviewing step?')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Peer review rubric')),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to=review.models.peerreview_directory_path)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Person')),
                ('pr_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.PR_process')),
            ],
        ),
        migrations.AddField(
            model_name='pr_process',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Rubric'),
        ),
    ]
