# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20170212_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='datetime_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date and time the learner/group submitted.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
