# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20170311_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricactual',
            name='completed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='When did user end grading?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubricactual',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rubricactual',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='When did user start grading?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubricactual',
            name='word_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubrictemplate',
            name='maximum_score',
            field=models.FloatField(default=0.0),
        ),
    ]
