# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20170212_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='QActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_displayed', models.TextField(blank=True)),
                ('given_answer', models.TextField(blank=True)),
                ('grading_answer', models.TextField(blank=True)),
                ('user_comments', models.TextField(blank=True)),
                ('last_edit', models.DateTimeField(auto_now=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('next_q', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_question', to='review.QActual')),
                ('prev_q', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_question', to='review.QActual')),
            ],
        ),
        migrations.CreateModel(
            name='QSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(editable=False)),
                ('announcement', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(editable=False, max_length=32)),
                ('q_type', models.CharField(choices=[('tf', 'True/False question'), ('mcq', 'Multiple choice question'), ('short', 'Short answer question'), ('long', 'Long answer question'), ('numeric', 'Numeric answer (with specified sensitivity)')], max_length=10)),
                ('max_grade', models.PositiveSmallIntegerField()),
                ('t_question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RubricTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Peer review rubric')),
                ('slug', models.SlugField(default='', editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='full_name',
            field=models.CharField(blank=True, max_length=400, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='pr_process',
            name='LTI_title',
            field=models.CharField(default='Default', help_text='In Brightspace LTI post: "resource_link_title"', max_length=300, verbose_name='LTI title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pr_process',
            name='uses_groups',
            field=models.BooleanField(default=False, help_text='The workflow and responses are slightly modified if groups are used.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_valid',
            field=models.BooleanField(default=False, help_text='Is invalid if it is too late, or if a newer submissionis replacing this one.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('T', 'Subitted late'), ('F', 'Finished'), ('L', 'Flagged'), ('G', 'Being peer-reviewed/graded'), ('N', 'Nothing submitted')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='pr_process',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.QTemplate'),
        ),
        migrations.AlterField(
            model_name='pr_process',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Your peer review title'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='pr_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.PR_process', verbose_name='Peer review'),
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
        migrations.AddField(
            model_name='qset',
            name='include',
            field=models.ManyToManyField(through='review.Inclusion', to='review.QTemplate'),
        ),
        migrations.AddField(
            model_name='qactual',
            name='qset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.QSet'),
        ),
        migrations.AddField(
            model_name='qactual',
            name='qtemplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.QTemplate'),
        ),
        migrations.AddField(
            model_name='qactual',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Person'),
        ),
        migrations.AddField(
            model_name='inclusion',
            name='qset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.QSet'),
        ),
        migrations.AddField(
            model_name='inclusion',
            name='qtemplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.QTemplate'),
        ),
    ]
