# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20170314_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0.0, help_text='Used to order the display of grade items')),
                ('explanation', models.TextField(help_text='HTML is possible; used in the template. Can include template elements.', max_length=500)),
                ('weight', models.FloatField(default=0.0, help_text=('Values must be between 0.0 and 1.0.', ' It is your responsibility to make sure the total weights do not sum to over 1.0 (i.e. 100%)'))),
                ('extra_detail', models.CharField(blank=True, choices=[('peer', 'peer'), ('instructor', 'instructor')], help_text=('Extra information used to help distinguish a phase. For ', 'example, the Peer-Evaluation phase is used for instructors as well as peers to evaluate. But the instructor(s) grades must get a higher weight. This is used to split the code.'), max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GradeReportPhase',
            fields=[
                ('prphase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='review.PRPhase')),
            ],
            bases=('review.prphase',),
        ),
        migrations.AlterField(
            model_name='prphase',
            name='end_dt',
            field=models.DateTimeField(blank=True, verbose_name='End of this phase'),
        ),
        migrations.AlterField(
            model_name='prphase',
            name='start_dt',
            field=models.DateTimeField(blank=True, verbose_name='Start of this phase'),
        ),
        migrations.AddField(
            model_name='gradecomponent',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.PRPhase'),
        ),
        migrations.AddField(
            model_name='gradecomponent',
            name='pr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.PR_process'),
        ),
    ]
