# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20170213_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('T', 'Subitted late'), ('F', 'Finished'), ('L', 'Flagged'), ('G', 'Being peer-reviewed/graded'), ('N', 'Nothing submitted yet')], default='N', max_length=2),
        ),
    ]
