# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20170315_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prphase',
            name='end_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End of this phase'),
        ),
        migrations.AlterField(
            model_name='prphase',
            name='start_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start of this phase'),
        ),
    ]
