# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20170315_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prphase',
            name='instructions',
        ),
        migrations.AddField(
            model_name='prphase',
            name='show_dates',
            field=models.BooleanField(default=True, help_text='Shows the dates in the user view'),
        ),
        migrations.AlterField(
            model_name='prphase',
            name='end_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End of this phase'),
        ),
        migrations.AlterField(
            model_name='prphase',
            name='start_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start of this phase'),
        ),
    ]
