# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20170213_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qactual',
            old_name='user',
            new_name='grader',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='learner',
            new_name='submitted_by',
        ),
        migrations.AddField(
            model_name='person',
            name='user_ID',
            field=models.CharField(blank=True, max_length=100, verbose_name='User ID from Brightspace'),
        ),
        migrations.AddField(
            model_name='pr_process',
            name='max_file_upload_size_MB',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_valid',
            field=models.BooleanField(default=False, help_text='Invalid if it is too late, or if a newer submissionis replacing this one.'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('T', 'Subitted late'), ('F', 'Finished'), ('G', 'Being peer-reviewed/graded'), ('N', 'Nothing submitted yet')], default='N', max_length=2),
        ),
    ]
