# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-15 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20170315_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecomponent',
            name='explanation',
            field=models.TextField(help_text=b'HTML is possible; used in the template. Can include template elements: {{self.grade_text}}, {{pr.___}}, {{self.n_peers}}, etc', max_length=500),
        ),
    ]
