# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20170216_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('Learn', 'Learner'), ('TA', 'Teaching Assistant')], default='Learn', max_length=5),
        ),
    ]
