# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_person_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='label',
            field=models.CharField(help_text="Obtain this from the HTML POST field: 'context_id' ", max_length=300, verbose_name='LTI POST label'),
        ),
    ]
