# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20170217_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='RItemActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RItemTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_required', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
                ('criterion', models.TextField(help_text='The prompt/criterion for the row in the rubric')),
                ('max_score', models.FloatField(help_text='Highest score achievable here')),
            ],
        ),
        migrations.CreateModel(
            name='ROPtionActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ROptionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Usually: 1, 2, 3, 4, etc points')),
                ('criterion', models.TextField(help_text='A prompt/criterion to the peers')),
                ('order', models.IntegerField()),
                ('rubric_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.RItemTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RubricActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('submitted', models.BooleanField(default=False)),
                ('graded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Person')),
            ],
        ),
        migrations.AddField(
            model_name='rubrictemplate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrictemplate',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roptionactual',
            name='roption_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.ROptionTemplate'),
        ),
        migrations.AddField(
            model_name='ritemtemplate',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.RubricTemplate'),
        ),
        migrations.AddField(
            model_name='ritemactual',
            name='ritem_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.RItemTemplate'),
        ),
    ]
