# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20170311_0034'),
        ('review', '0008_auto_20170318_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('unique_code', models.CharField(blank=True, editable=False, max_length=16)),
                ('group', models.ForeignKey(blank=True, default=None, help_text='If a group submission, links to group.', null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Person')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.PRPhase')),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Submission')),
            ],
        ),
    ]
