# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_reviewreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecomponent',
            name='name_in_table',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
