# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20170217_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inclusion',
            name='qset',
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='qtemplate',
        ),
        migrations.RemoveField(
            model_name='qactual',
            name='grader',
        ),
        migrations.RemoveField(
            model_name='qactual',
            name='next_q',
        ),
        migrations.RemoveField(
            model_name='qactual',
            name='prev_q',
        ),
        migrations.RemoveField(
            model_name='qactual',
            name='qset',
        ),
        migrations.RemoveField(
            model_name='qactual',
            name='qtemplate',
        ),
        migrations.RemoveField(
            model_name='qset',
            name='include',
        ),
        migrations.AddField(
            model_name='ritemactual',
            name='as_displayed',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pr_process',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.RubricTemplate'),
        ),
        migrations.DeleteModel(
            name='Inclusion',
        ),
        migrations.DeleteModel(
            name='QActual',
        ),
        migrations.DeleteModel(
            name='QSet',
        ),
        migrations.DeleteModel(
            name='QTemplate',
        ),
    ]
