# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_gradecomponent_name_in_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecomponent',
            name='explanation',
            field=models.TextField(help_text='HTML is possible; used in the template. Can include template elements: {{grade_text}}, {{pr.___}}, etc.', max_length=500),
        ),
    ]
