# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_auto_20170217_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricactual',
            name='rubric_template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='review.RubricTemplate'),
            preserve_default=False,
        ),
    ]
