# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_auto_20170320_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecomponent',
            name='extra_detail',
            field=models.CharField(blank=True, choices=[('Learn', 'Learn'), ('Admin', 'Admin')], help_text=('Extra information used to help distinguish a phase. For ', 'example, the Peer-Evaluation phase is used for instructors as well as peers to evaluate. But the instructor(s) grades must get a higher weight. This is used to split the code.'), max_length=50),
        ),
    ]
