# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_rubricactual_rubric_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pr_process',
            name='course',
        ),
        migrations.RemoveField(
            model_name='pr_process',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='pr_process',
        ),
        migrations.DeleteModel(
            name='PR_process',
        ),
    ]
