# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_auto_20170217_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pr_process',
            old_name='peer_reviews_completed_by',
            new_name='dt_peer_reviews_completed_by',
        ),
        migrations.RenameField(
            model_name='pr_process',
            old_name='peer_reviews_received_back',
            new_name='dt_peer_reviews_received_back',
        ),
        migrations.RenameField(
            model_name='pr_process',
            old_name='peer_reviews_start_by',
            new_name='dt_peer_reviews_start_by',
        ),
        migrations.RenameField(
            model_name='pr_process',
            old_name='submission_deadline',
            new_name='dt_submission_deadline',
        ),
    ]
