# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_auto_20170218_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='pr_process',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='rubrictemplate',
            name='id',
        ),
        migrations.AddField(
            model_name='rubricactual',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Submission'),
        ),
        migrations.AddField(
            model_name='rubrictemplate',
            name='pr_process',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='review.PR_process'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='number_reviews_assigned',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times this submission has been assigned'),
        ),
        migrations.AddField(
            model_name='submission',
            name='number_reviews_completed',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times this submission has been completed'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_valid',
            field=models.BooleanField(default=False, help_text='Valid if: it was submitted on time, or if this is the most recent submission (there might be older ones).'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('T', 'Submitted late'), ('F', 'Finished'), ('G', 'Being peer-reviewed/graded'), ('N', 'Nothing submitted yet')], default='N', max_length=2),
        ),
    ]
