# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_viewallsubmissionsphase'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionphase',
            name='send_email_on_success',
            field=models.BooleanField(default=True),
        ),
    ]
