# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_submissionphase_send_email_on_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=review.models.peerreview_directory_path),
        ),
    ]
