# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_auto_20170221_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr_process',
            name='number_of_reviews_per_learner',
            field=models.PositiveIntegerField(default=3, help_text='How many reviews must each learner complete?'),
        ),
        migrations.AlterField(
            model_name='rubricactual',
            name='submitted',
            field=models.BooleanField(default=False, help_text='Has been completed reviewed AND submitted by peer grader.'),
        ),
    ]
