# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_submission_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roptiontemplate',
            name='short_text',
        ),
    ]
