# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_auto_20170221_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricactual',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Submission'),
        ),
        migrations.AddField(
            model_name='submission',
            name='number_reviews_assigned',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times this submission has been assigned'),
        ),
        migrations.AddField(
            model_name='submission',
            name='number_reviews_completed',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times this submission has been completed'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('T', 'Submitted late'), ('F', 'Finished'), ('G', 'Being peer-reviewed/graded'), ('N', 'Nothing submitted yet')], default='N', max_length=2),
        ),
    ]
