# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_auto_20170221_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ritemactual',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
