# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_remove_roptiontemplate_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecomponent',
            name='mandatory',
            field=models.BooleanField(default=False, help_text='If this is True, and the learners get a zero for this component, the entire grade is zero. It creates an if-else type grading.'),
        ),
    ]
