# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_auto_20170221_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritemactual',
            name='r_actual',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='review.RubricActual'),
            preserve_default=False,
        ),
    ]
