# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0019_ritemactual_r_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricactual',
            name='unique_code',
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
    ]
