# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0020_rubricactual_unique_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ritemtemplate',
            old_name='rubric',
            new_name='r_template',
        ),
        migrations.AddField(
            model_name='rubrictemplate',
            name='general_instructions',
            field=models.TextField(default=''),
        ),
    ]
