# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0021_auto_20170222_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='roptionactual',
            name='comment',
            field=models.TextField(blank=True, max_length=''),
        ),
        migrations.AddField(
            model_name='roptionactual',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roptionactual',
            name='graded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Person'),
        ),
        migrations.AddField(
            model_name='roptionactual',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
