# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0022_auto_20170222_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roptionactual',
            name='graded_by',
        ),
        migrations.AddField(
            model_name='roptionactual',
            name='ritem_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.RItemActual'),
        ),
    ]
