# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0023_auto_20170409_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricactual',
            name='special_access',
            field=models.BooleanField(default=False, help_text='Set to true to allow the "graded_by" person to access it.'),
        ),
    ]
