# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0024_auto_20170222_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricactual',
            name='status',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
