# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0024_rubricactual_special_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetAllOwnSubmissionsPhase',
            fields=[
                ('prphase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='review.PRPhase')),
            ],
            bases=('review.prphase',),
        ),
    ]
