# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0025_getallownsubmissionsphase'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='base_url',
            field=models.CharField(blank=True, help_text='The base URL', max_length=200),
        ),
    ]
