# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-23 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0026_auto_20170222_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr_process',
            name='dt_peer_reviews_received_back',
            field=models.DateTimeField(verbose_name=b'When will learners receive their results back?'),
        ),
    ]
