# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0029_auto_20170223_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr_process',
            name='LTI_title',
            field=models.CharField(help_text='A title to identiy this PR in the database"', max_length=300, verbose_name='LTI Title'),
        ),
    ]
