# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0030_auto_20170226_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr_process',
            name='LTI_id',
            field=models.CharField(default=0, help_text='In Brightspace LTI post: "resource_link_id"', max_length=50, verbose_name='LTI ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pr_process',
            name='LTI_title',
            field=models.CharField(help_text='A title to identify this PR in the database"', max_length=300, verbose_name='LTI Title'),
        ),
    ]
