# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0031_auto_20170226_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr_process',
            name='LTI_title',
            field=models.CharField(help_text=b'A title to identify this PR in the database', max_length=300, verbose_name=b'LTI Title'),
        ),
    ]
