# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0034_person_student_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AddField(
            model_name='course',
            name='offering',
            field=models.PositiveIntegerField(blank=True, default='0000', help_text='Which year/quarter is it being offered?'),
        ),
    ]
