# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0035_auto_20170226_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, help_text='NOT USED'),
        ),
    ]
