# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0036_auto_20170226_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr_process',
            name='accepted_file_types_comma_separated',
            field=models.CharField(default='PDF', help_text='Comma separated list, for example: pdf, docx, doc', max_length=100),
        ),
    ]
