# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20170301_2008'),
        ('review', '0037_pr_process_accepted_file_types_comma_separated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr_process',
            name='gf_process',
            field=models.ForeignKey(blank=True, default=None, help_text='Must be specified if groups are being used.', null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group_Formation_Process'),
        ),
    ]
