# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20170301_2008'),
        ('review', '0038_pr_process_gf_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='group_submitted',
            field=models.ForeignKey(blank=True, default=None, help_text='If a group submission, it links back to it.', null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
