# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0041_auto_20170303_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionphase',
            old_name='pr_process',
            new_name='pr',
        ),
        migrations.RemoveField(
            model_name='pr_process',
            name='accepted_file_types_comma_separated',
        ),
        migrations.RemoveField(
            model_name='pr_process',
            name='max_file_upload_size_MB',
        ),
    ]
