# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0044_selfevaluationphase'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPhase',
            fields=[
                ('prphase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='review.PRPhase')),
            ],
            bases=('review.prphase',),
        ),
        migrations.CreateModel(
            name='PeerEvaluationPhase',
            fields=[
                ('prphase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='review.PRPhase')),
                ('number_of_reviews_per_learner', models.PositiveIntegerField(default=3, help_text='How many reviews must each learner complete?')),
            ],
            bases=('review.prphase',),
        ),
        migrations.RemoveField(
            model_name='pr_process',
            name='number_of_reviews_per_learner',
        ),
        migrations.RemoveField(
            model_name='pr_process',
            name='show_rubric_prior_to_submission',
        ),
    ]
