# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0045_auto_20170303_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='prphase',
            name='name',
            field=models.CharField(default='... Phase ...', max_length=50),
        ),
        migrations.AlterField(
            model_name='prphase',
            name='end_dt',
            field=models.DateTimeField(verbose_name='End of this phase'),
        ),
        migrations.AlterField(
            model_name='prphase',
            name='start_dt',
            field=models.DateTimeField(verbose_name='Start of this phase'),
        ),
    ]
