# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0047_prphase_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='phase',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.PRPhase', verbose_name='Attached with which phase'),
        ),
    ]
