# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0048_submission_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricactual',
            name='status',
            field=models.CharField(choices=[('A', 'Assigned to grader'), ('P', 'Progressing...'), ('C', 'Completed')], default='A', max_length=2),
        ),
    ]
