# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0049_auto_20170305_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrictemplate',
            name='phase',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.PRPhase'),
        ),
    ]
