# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0050_rubrictemplate_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='roptiontemplate',
            name='short_text',
            field=models.CharField(default='', help_text='This text is in the drop down', max_length=50),
        ),
        migrations.AlterField(
            model_name='roptiontemplate',
            name='option_type',
            field=models.CharField(choices=[('Radio', 'Radio buttons (default)'), ('DropD', 'Dropdown of score'), ('LText', 'Long text [HTML Text area]'), ('SText', 'Short text [HTML input=text]')], default='Radio', max_length=5),
        ),
    ]
