# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0051_auto_20170305_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roptiontemplate',
            name='criterion',
            field=models.TextField(blank=True, help_text='A prompt/criterion to the peers'),
        ),
        migrations.AlterField(
            model_name='roptiontemplate',
            name='short_text',
            field=models.CharField(blank=True, default='', help_text='This text is in the drop down', max_length=50),
        ),
    ]
