# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0053_auto_20170305_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrictemplate',
            name='show_order',
            field=models.BooleanField(default=True, help_text='Shows the order numbers. e.g 1. Assess ...; else it just show: Assess ...'),
        ),
    ]
