# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0056_auto_20170305_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roptiontemplate',
            name='option_type',
        ),
    ]
