# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0057_remove_roptiontemplate_option_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prphase',
            options={'verbose_name': 'PR phase', 'verbose_name_plural': 'PR phases'},
        ),
    ]
