# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0058_auto_20170309_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='full_name',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='pr_process',
            name='dt_peer_reviews_completed_by',
        ),
        migrations.RemoveField(
            model_name='pr_process',
            name='dt_peer_reviews_received_back',
        ),
        migrations.RemoveField(
            model_name='pr_process',
            name='dt_peer_reviews_start_by',
        ),
        migrations.RemoveField(
            model_name='pr_process',
            name='dt_submission_deadline',
        ),
        migrations.RemoveField(
            model_name='pr_process',
            name='dt_submissions_open_up',
        ),
        migrations.RemoveField(
            model_name='pr_process',
            name='make_submissions_visible_after_review',
        ),
        migrations.RemoveField(
            model_name='pr_process',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='rubrictemplate',
            name='slug',
        ),
        migrations.AlterField(
            model_name='pr_process',
            name='LTI_system',
            field=models.CharField(choices=[('Brightspace-v1', 'Brightspace-v1'), ('edX-v1', 'edX-v1'), ('Coursera-v1', 'Coursera-v1')], max_length=50),
        ),
    ]
