# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0059_auto_20170310_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
    ]
