# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0060_remove_person_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='display_name',
            field=models.CharField(blank=True, max_length=400, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_ID',
            field=models.CharField(blank=True, max_length=100, verbose_name='User ID from LMS/LTI'),
        ),
    ]
