# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyterms', '0003_auto_20170717_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyterm_definition',
            options={'verbose_name': 'Key Term Definition', 'verbose_name_plural': 'Key Term Definitions'},
        ),
        migrations.AlterModelOptions(
            name='keyterm_task',
            options={'verbose_name': 'Key Term Task', 'verbose_name_plural': 'Key Term Tasks'},
        ),
        migrations.AlterModelOptions(
            name='thumbs',
            options={'verbose_name': 'Thumbs up', 'verbose_name_plural': 'Thumbs up'},
        ),
        migrations.AlterField(
            model_name='keyterm_definition',
            name='allow_to_share',
            field=models.BooleanField(default=True, help_text='Student is OK to share their work with class.'),
        ),
        migrations.AlterField(
            model_name='keyterm_definition',
            name='explainer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyterm_definition',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='User has submitted, and it is after the deadline'),
        ),
        migrations.AlterField(
            model_name='keyterm_definition',
            name='reference_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
