# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import keyterms.models


class Migration(migrations.Migration):

    dependencies = [
        ('keyterms', '0004_auto_20170720_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyterm_task',
            name='deadline_for_voting',
            field=models.DateTimeField(default=keyterms.models.get_deadline),
        ),
    ]
