# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0033_auto_20170226_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Group name')),
                ('description', models.TextField(blank=True, verbose_name='Detailed group description')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='How many people in this particular group instance   ')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Formation_Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LTI_system', models.CharField(choices=[('Brightspace-v1', 'Brightspace-v1'), ('edX-v1', 'edX-v1')], max_length=50)),
                ('title', models.CharField(max_length=300, verbose_name='Group formation')),
                ('LTI_id', models.CharField(help_text='In Brightspace LTI post: "resource_link_id"', max_length=50, verbose_name='LTI ID')),
                ('instructions', models.TextField(help_text='May contain HTML instructions', verbose_name='Overall instructions to learners')),
                ('dt_groups_open_up', models.DateTimeField(verbose_name='When can learners start to register')),
                ('dt_selfenroll_starts', models.DateTimeField(verbose_name='Usually the same as above date/time, but can be later')),
                ('dt_group_selection_stops', models.DateTimeField(verbose_name='When does group selection stop')),
                ('allow_unenroll', models.BooleanField(default=True, help_text='Can learners unenroll, which implies they will also be allowed to re-enroll, until the close off date/time.')),
                ('show_fellows', models.BooleanField(default=False, help_text='Can learners see the FirstName LastName of the other people enrolled in their groups.')),
                ('show_description', models.BooleanField(default=True, help_text='Should we show the group descriptions also?')),
                ('random_add_unenrolled_after_cutoff', models.BooleanField(default=False, help_text='Should we randomly allocate unenrolled users after the cut-off date/time ("dt_group_selection_stops")?')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Course')),
            ],
            options={
                'verbose_name': 'Group formation process',
                'verbose_name_plural': 'Group formation processes',
            },
        ),
    ]
