# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-10 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_formation_process',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Course'),
        ),
        migrations.AddField(
            model_name='group',
            name='gp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group_Formation_Process'),
        ),
        migrations.AddField(
            model_name='enrolled',
            name='group',
            field=models.ForeignKey(help_text=b'If blank/null: used internally to enrol the rest of the class list.', null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
        migrations.AddField(
            model_name='enrolled',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Person'),
        ),
    ]
