# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20170226_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='gp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='groups.Group_Formation_Process'),
            preserve_default=False,
        ),
    ]
