# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_gp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='group',
            field=models.ForeignKey(help_text='If blank/null: used internally to enrol the rest of the class list.', null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
