# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20170226_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_formation_process',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Group formation name'),
        ),
    ]
