# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20170301_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='For ordering purposes in the tables.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='How many people in this particular group instance?'),
        ),
    ]
